server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      orchestrator: orchestrator
      finish-success: finish-success
      finish-fail: finish-fail
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

    data:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}

logging:
  level:
    org:
      apache:
        kafka: OFF